kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: epistola
data:
  nginx.conf: |
    server {
      listen 80;
      index index.php index.html;
      server_name localhost;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /code;

      location ~ \.php$ {
          include fastcgi_params;

          try_files $uri = 404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass kubem.ceti.gr:31558;
          fastcgi_index index.php;
          
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }