apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: epistola
  labels:
    app: flask-api
spec:
  ports:
    - port: 10100         
      targetPort: 80       
  selector:
    app: flask-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-d
  namespace: epistola
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: spa-a4p-flask-api
        image: epistola/flask-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10100
          name: http
          protocol: TCP
      restartPolicy: Always
      serviceAccountName: ""