apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mng-httpproxy-eu
  namespace: epistola
spec:
  virtualhost:
    fqdn: mng.agro4plus.eu
  routes:
    - conditions:
      - prefix: /
      services:
        - name: a4p-mgmt-service
          port: 9021
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mng-httpproxy-gr
  namespace: epistola
spec:
  virtualhost:
    fqdn: mng.agro4plus.gr
  routes:
    - conditions:
      - prefix: /
      services:
        - name: a4p-mgmt-service
          port: 9021
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mgmt-httpproxy-eu
  namespace: epistola
spec:
  virtualhost:
    fqdn: management.agro4plus.eu
  routes:
    - conditions:
      - prefix: /
      services:
        - name: a4p-mgmt-service
          port: 9021
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mgmt-httpproxy-gr
  namespace: epistola
spec:
  virtualhost:
    fqdn: management.agro4plus.gr
  routes:
    - conditions:
      - prefix: /
      services:
        - name: a4p-mgmt-service
          port: 9021