apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: spa-httpproxy
  namespace: epistola
spec:
  virtualhost:
    fqdn: spa.agro4plus.eu
  routes:
    - conditions:
      - prefix: /
      services:
        - name: a4p-spa-service
          port: 9032
  virtualhost:
    fqdn: spa.agro4plus.gr
  routes:
    - conditions:
      - prefix: /
      services:
        - name: a4p-spa-service
          port: 9032