kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: epistola
data:
  nginx.conf: |
    server {
      
      listen 80 default_server;
      listen [::]:80 default_server;
      index /obj/default/dashboard.php;

      # Set nginx to serve files from the shared volume!
      root /code;
      server_name _;
      #rewrite ^/src/obj/(.*)$ $1 last;

      location / {
        #try_files $uri $uri/src/obj/default/dashboard.php;
        try_files $uri $uri/ =404;
      }

      # location = / {
      #     return 301 http://$host/src/obj/default/dashboard.php;
      # }
      
      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index /obj/default/dashboard.php;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php-service.epistola:9000;
      }

    }