apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-www-claim-spa
    namespace: epistola
spec:
    storageClassName: chaos-nfs-storage
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi