apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: "chaos-nfs-storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  # nfs:
  #   path: "/mnt/data"
  #   server: chaos.ceti.gr
  