apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: invs-httpproxy
  namespace: epistola
spec:
  virtualhost:
    fqdn: invest.agro4plus.eu
  routes:
    - conditions:
      - prefix: /
      services:
        - name: wordpress
          port: 9080
  virtualhost:
    fqdn: invest.agro4plus.gr
  routes:
    - conditions:
      - prefix: /
      services:
        - name: wordpress
          port: 9080