apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  namespace: epistola
spec:
  ports:
    - port: 9080
      targetPort: 80
      nodePort: 31788
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
  namespace: epistola
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
  namespace: epistola
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: kubem.ceti.gr:30002
        - name: WORDPRESS_DB_NAME
          value: invs_a4p_platform
        - name: WORDPRESS_DB_USER
          value: chairiq
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-pass-khhg788hc8
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/sh", "-c", "echo 'AddType application/vnd.android.package-archive .apk' >> /etc/apache2/mods-available/mime.conf; echo 'application/vnd.android.package-archive     apk' >> /etc/mime/types; service apache2 restart"]
      nodeName: chaos
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim